# Generated by Django 5.2.11 on 2026-03-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_art_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='changed_by',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
